apiVersion: skaffold/v1
kind: Config
build: 
  artifacts: 
    - image: viramdhangarregistry.azurecr.io/demos/skaffold-spring-boot-example
      jib: {}
  local: {}
 
deploy: 
  kubectl: 
    manifests: 
     - k8s-*